### ISSUE TITLE
Fix incorrect versions of plugins in migration v1.0 to beta guide

### ISSUE THREAD

**Issue by Viijay-Kr** [tauri-apps/tauri-docs#2079]
The version information of some plugins  in migration guide is misleading . The auto migration command also fails to install the right plugins . 
Manually adding the dependencies to the cargo.toml using the specified version number from the doc also fails . 
Thanks to rust-analyzer I was able to add the correct version number. 

I think this doc should convey the correct version numbers other than just specifying "2" as version number. 

https://beta.tauri.app/guides/upgrade-migrate/from-tauri-1

Currently the following plugins resulted in a failure for me if I follow the migration documentation and use "2" as version
```toml
tauri = { version = "2.0.0-beta", features = [] }
tauri-plugin-clipboard-manager = { version = "2.1.0-beta.1" }
tauri-plugin-shell = "2.0.0-beta.3"
[target."cfg(not(any(target_os = \"android\", target_os = \"ios\")))".dependencies]
tauri-plugin-global-shortcut = { version = "2.0.0-beta.3" }
tauri-plugin-http = { version = "2.0.0-beta.5" }
```
