### ISSUE TITLE
[docs] v2 Sidecar Rust example is missing init()

### ISSUE THREAD

**Issue by jviel** [tauri-apps/tauri-docs#2704]
I am brand new to Rust so maybe a noob mistake.
I was attempting to follow [the v2 sidecar guide](https://v2.tauri.app/develop/sidecar/#running-it-from-rust)
using ShellExt.

On Windows 10
`rustc 1.80.0 (051478957 2024-07-21)`
```toml
# Cargo.toml
...
[build-dependencies]
tauri-build = { version = "2.0.0-rc", features = [] }

[dependencies]
tauri = { version = "2.0.0-rc", features = [] }
tauri-plugin-shell = "2.0.0-rc"

```

It seems it's not enough to import ShellExt and just use it - as described in the doc. 

```rust
#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

use tauri_plugin_shell::ShellExt;

fn main() {
    tauri::Builder::default()
        .setup(|app| {
            let sidecar = app.shell().sidecar("my-sidecar");
...
```
That causes the following error:
```shell
thread 'main' panicked at C:\...\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tauri-2.0.0-rc.15\src/lib.rs:716:8:
state() called before manage() for given type
...
[0918/130641.874:ERROR:window_impl.cc(121)] Failed to unregister class Chrome_WidgetWin_0. Error = 1412
```

***FIX***: Adding the init line fixed it for me:
```rust
fn main() {
    tauri::Builder::default()
        .plugin(tauri_plugin_shell::init())  // <--- this line
        .setup(|app| {
            let sidecar_simio = app.shell().sidecar("sim-io");
```
