### ISSUE TITLE
Add guide: Conditional compilation

### ISSUE THREAD

**Issue by JonasKruckenberg** [tauri-apps/tauri-docs#444]
# TODO

Tauri exposes several environment variables to the `beforeDevCommand` and `beforeBuildCommand`, allowing frontend bundlers to perform conditional compilation. You can use this to write platform-specific JS code.

# Details

## JavaScript
- only available with some bundlers (but most) -> called treeshaking
- the cli exposes a set of environment variables
   - `TAURI_PLATFORM` - same as `target_os`
   - `TAURI_ARCH` - same as `target_arch`
   - `TAURI_FAMILY` - same as `target_family`
   - `TAURI_PLATFORM_VERSION` - version of the OS
   - `TAURI_PLATFORM_TYPE` - `"Linux" | "Darwin" | "Window_NT"` same as nodejs `os.type()`
   - `TAURI_DEBUG` - same as `debug_assertions`

- quick example

## Rust
- link to conditional compilation guide https://doc.rust-lang.org/reference/conditional-compilation.html
- quick intro `cfg!` and `#[cfg()]`
- quick intro features
- target a specific OS (`target_os` and `target_family`)
- target a specific CPU architecture
- `cfg(debug_assertions)`

**Comment by simonhyll** [comment]
We definitely need a guide on this one way or another, possibly under the Develop guide section.
Tracking for 2.0.

**Comment by stewartadam** [comment]
If others are looking to conditionally compile **backend** code for Tauri builds, you can define a `tauri` feature in your `Cargo.toml` that targets your tauri dependencies:

```toml
# ...
[build-dependencies]
tauri-build = { version = "2", features = [], optional = true }

[dependencies]
tauri = { version = "2", features = [], optional = true }
tauri-plugin-opener = { version = "2", optional = true }

[features]
tauri = ["dep:tauri", "dep:tauri-build", "dep:tauri-plugin-opener"] # meta-feature for enabling Tauri app
```

In tauri.config.json, specify that feature to be enabled for tauri builds:
```
// ...
"build": {
  "features": ["tauri"],
}
```

Example main.rs:
```
# ...
fn main() {
    #[cfg(feature = "tauri")]
    tauri_app_lib::run_tauri();

    #[cfg(not(feature = "tauri"))]
    tauri_app_lib::run_without_turi();
}
```

Example lib.rs:
```
#[cfg(feature = "tauri")]
#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run_tauri() {
    tauri::Builder::default()
        .plugin(tauri_plugin_opener::init())
        .invoke_handler(tauri::generate_handler![greet])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}

pub fn run_without_tauri() {
    # ...
}
```

This is handy for apps that have their own lifecycle, in my case it's because I've integrated a Bevy ECS runtime into my Tauri app. It's useful to quickly run the app outside a full Tauri shell for quick iteration and then I package builds once the code is stable.
